// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package rest

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyScopes              = "ApiKey.Scopes"
	BasicAuthenticationScopes = "BasicAuthentication.Scopes"
	OAuth2Scopes              = "OAuth2.Scopes"
)

// AddressMetadata defines model for addressMetadata.
type AddressMetadata struct {
	Comment     string `json:"comment"`
	ServiceName string `json:"service_name"`
}

// AliasData Address of type "alias" data structure
type AliasData struct {
	// Email Email of the Alias
	Email openapi_types.Email `json:"email"`

	// ForwardEmail forward email for alias address
	ForwardEmail openapi_types.Email `json:"forward_email"`

	// Id alias address id
	Id       string          `json:"id"`
	Metadata AddressMetadata `json:"metadata"`
	Owner    UserData        `json:"owner"`
}

// BasicAuthForm defines model for basicAuthForm.
type BasicAuthForm struct {
	Password string `json:"password"`

	// User user name
	User string `json:"user"`
}

// ChainData defines model for chainData.
type ChainData struct {
	FromEmail string `json:"from_email"`
	Hash      string `json:"hash"`
	ToEmail   string `json:"to_email"`
}

// Error defines model for error.
type Error struct {
	// Id error id
	Id float32 `json:"id"`

	// Msg error description
	Msg string `json:"msg"`
}

// ProtectedAddressData defines model for protectedAddressData.
type ProtectedAddressData struct {
	Email    openapi_types.Email `json:"email"`
	Id       string              `json:"id"`
	Metadata AddressMetadata     `json:"metadata"`
	Owner    UserData            `json:"owner"`
}

// UserData defines model for userData.
type UserData struct {
	// FailedAttempts number of failed authentication attempts
	FailedAttempts *float32 `json:"failed_attempts,omitempty"`

	// FirstName user first name
	FirstName string `json:"first_name"`

	// Id user id
	Id string `json:"id"`

	// LastName user last name
	LastName string `json:"last_name"`

	// LockoutUntil date/time the user account was lockout until
	LockoutUntil *string `json:"lockout_until,omitempty"`

	// Login user login
	Login openapi_types.Email `json:"login"`

	// Type user type
	Type string `json:"type"`
}

// HTTP400 defines model for HTTP400.
type HTTP400 = Error

// HTTP401 defines model for HTTP401.
type HTTP401 = Error

// HTTP403 defines model for HTTP403.
type HTTP403 = Error

// HTTP404 defines model for HTTP404.
type HTTP404 = Error

// AuthForm defines model for authForm.
type AuthForm = BasicAuthForm

// BasicAuthenticationTokenResponse defines model for basicAuthenticationTokenResponse.
type BasicAuthenticationTokenResponse struct {
	// Expiry time of token expiration
	Expiry string `json:"expiry"`

	// Token signed JWT token for stateless authentication
	Token string `json:"token"`
}

// CreateAliasResponse Address of type "alias" data structure
type CreateAliasResponse = AliasData

// CreateEmailChainResponse defines model for createEmailChainResponse.
type CreateEmailChainResponse = ChainData

// CreatePrAddrResponse defines model for createPrAddrResponse.
type CreatePrAddrResponse = ProtectedAddressData

// CreateUserResponse defines model for createUserResponse.
type CreateUserResponse = UserData

// ErrorResponse defines model for errorResponse.
type ErrorResponse struct {
	Id  float32 `json:"id"`
	Msg string  `json:"msg"`
}

// GetAliasDetailsResponse Address of type "alias" data structure
type GetAliasDetailsResponse = AliasData

// GetAliasesResponse defines model for getAliasesResponse.
type GetAliasesResponse = []AliasData

// GetEmailChainDetailsResponse defines model for getEmailChainDetailsResponse.
type GetEmailChainDetailsResponse = ChainData

// GetPrAddrDetailsResponse defines model for getPrAddrDetailsResponse.
type GetPrAddrDetailsResponse = ProtectedAddressData

// GetPrAddrsResponse defines model for getPrAddrsResponse.
type GetPrAddrsResponse = []ProtectedAddressData

// GetUserDetailsResponse defines model for getUserDetailsResponse.
type GetUserDetailsResponse = UserData

// GetUsersResponse defines model for getUsersResponse.
type GetUsersResponse = []UserData

// UpdateAliasResponse Address of type "alias" data structure
type UpdateAliasResponse = AliasData

// UpdatePrAddrResponse defines model for updatePrAddrResponse.
type UpdatePrAddrResponse = ProtectedAddressData

// UpdateUserResponse defines model for updateUserResponse.
type UpdateUserResponse = UserData

// CreateAliasRequest defines model for createAliasRequest.
type CreateAliasRequest struct {
	Metadata           AddressMetadata `json:"metadata"`
	ProtectedAddressId string          `json:"protected_address_id"`
}

// CreateEmailChain defines model for createEmailChain.
type CreateEmailChain struct {
	FromEmail openapi_types.Email `json:"from_email"`
	ToEmail   openapi_types.Email `json:"to_email"`
}

// CreateProtectedAddressRequest defines model for createProtectedAddressRequest.
type CreateProtectedAddressRequest struct {
	Email    string          `json:"email"`
	Metadata AddressMetadata `json:"metadata"`
}

// CreateUserRequest defines model for createUserRequest.
type CreateUserRequest struct {
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Login     string  `json:"login"`
	Password  *string `json:"password,omitempty"`
	Type      string  `json:"type"`
}

// UpdateAliasRequest defines model for updateAliasRequest.
type UpdateAliasRequest struct {
	Metadata           *AddressMetadata `json:"metadata,omitempty"`
	ProtectedAddressId *string          `json:"protected_address_id,omitempty"`
}

// UpdateProtectedAddressRequest defines model for updateProtectedAddressRequest.
type UpdateProtectedAddressRequest struct {
	Metadata *AddressMetadata `json:"metadata,omitempty"`
}

// UpdateUserRequest defines model for updateUserRequest.
type UpdateUserRequest struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName  *string `json:"last_name,omitempty"`
	Type      *string `json:"type,omitempty"`
}

// GetAliasesParams defines parameters for GetAliases.
type GetAliasesParams struct {
	// Owner owner ID to fetch parameters for
	Owner string `form:"owner" json:"owner"`
}

// CreateAliasJSONBody defines parameters for CreateAlias.
type CreateAliasJSONBody struct {
	Metadata           AddressMetadata `json:"metadata"`
	ProtectedAddressId string          `json:"protected_address_id"`
}

// UpdateAliasJSONBody defines parameters for UpdateAlias.
type UpdateAliasJSONBody struct {
	Metadata           *AddressMetadata `json:"metadata,omitempty"`
	ProtectedAddressId *string          `json:"protected_address_id,omitempty"`
}

// GetPrAddrsParams defines parameters for GetPrAddrs.
type GetPrAddrsParams struct {
	Id    *string `form:"id,omitempty" json:"id,omitempty"`
	Email *string `form:"email,omitempty" json:"email,omitempty"`
}

// CreatePrAddrJSONBody defines parameters for CreatePrAddr.
type CreatePrAddrJSONBody struct {
	Email    string          `json:"email"`
	Metadata AddressMetadata `json:"metadata"`
}

// UpdatePrAddrJSONBody defines parameters for UpdatePrAddr.
type UpdatePrAddrJSONBody struct {
	Metadata *AddressMetadata `json:"metadata,omitempty"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody struct {
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Login     string  `json:"login"`
	Password  *string `json:"password,omitempty"`
	Type      string  `json:"type"`
}

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName  *string `json:"last_name,omitempty"`
	Type      *string `json:"type,omitempty"`
}

// GetAuthFormParams defines parameters for GetAuthForm.
type GetAuthFormParams struct {
	Provider *string `form:"provider,omitempty" json:"provider,omitempty"`
	Code     *string `form:"code,omitempty" json:"code,omitempty"`
}

// CreateChainJSONBody defines parameters for CreateChain.
type CreateChainJSONBody struct {
	FromEmail openapi_types.Email `json:"from_email"`
	ToEmail   openapi_types.Email `json:"to_email"`
}

// CreateAliasJSONRequestBody defines body for CreateAlias for application/json ContentType.
type CreateAliasJSONRequestBody CreateAliasJSONBody

// UpdateAliasJSONRequestBody defines body for UpdateAlias for application/json ContentType.
type UpdateAliasJSONRequestBody UpdateAliasJSONBody

// CreatePrAddrJSONRequestBody defines body for CreatePrAddr for application/json ContentType.
type CreatePrAddrJSONRequestBody CreatePrAddrJSONBody

// UpdatePrAddrJSONRequestBody defines body for UpdatePrAddr for application/json ContentType.
type UpdatePrAddrJSONRequestBody UpdatePrAddrJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody

// CreateChainJSONRequestBody defines body for CreateChain for application/json ContentType.
type CreateChainJSONRequestBody CreateChainJSONBody
