// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package rest

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiTokenScopes            apiTokenContextKey            = "ApiToken.Scopes"
	BasicAuthenticationScopes basicAuthenticationContextKey = "BasicAuthentication.Scopes"
	OAuth2Scopes              oAuth2ContextKey              = "OAuth2.Scopes"
)

// Defines values for DomainType.
const (
	Global   DomainType = "global"
	Personal DomainType = "personal"
)

// Valid indicates whether the value is a known member of the DomainType enum.
func (e DomainType) Valid() bool {
	switch e {
	case Global:
		return true
	case Personal:
		return true
	default:
		return false
	}
}

// AddressMetadata defines model for addressMetadata.
type AddressMetadata struct {
	Comment     *string `json:"comment,omitempty"`
	ServiceName *string `json:"service_name,omitempty"`
}

// AliasData Address of type "alias" data structure
type AliasData struct {
	// Active Indicates whether the Alias is active and can be used
	Active *bool `json:"active,omitempty"`

	// Email Email of the Alias
	Email openapi_types.Email `json:"email"`

	// ForwardEmail forward email for alias address
	ForwardEmail openapi_types.Email `json:"forward_email"`

	// Id alias address id
	Id       string          `json:"id"`
	Metadata AddressMetadata `json:"metadata"`
	Owner    UserData        `json:"owner"`
}

// ApiTokenData defines model for apiTokenData.
type ApiTokenData struct {
	// Active Indicates whether the API token is active and can be used
	Active bool `json:"active"`

	// Description Optional details about the API token
	Description *string `json:"description,omitempty"`

	// Expiration Time of expiration of the API token
	Expiration time.Time `json:"expiration"`

	// Id API token ULID ID
	Id *string `json:"id,omitempty"`

	// Name Name of the API token
	Name string `json:"name"`
}

// ApiTokenDataOnCreate defines model for apiTokenDataOnCreate.
type ApiTokenDataOnCreate struct {
	// Active Indicates whether the API token is active and can be used
	Active bool `json:"active"`

	// ApiToken Clear text API token value; only returned when API token created first time
	ApiToken string `json:"api_token"`

	// Description Optional details about the API token
	Description *string `json:"description,omitempty"`

	// Expiration Time of expiration of the API token
	Expiration time.Time `json:"expiration"`

	// Id API token ULID ID
	Id *string `json:"id,omitempty"`

	// Name Name of the API token
	Name string `json:"name"`
}

// BasicAuthForm defines model for basicAuthForm.
type BasicAuthForm struct {
	Password string `json:"password"`

	// User user name
	User string `json:"user"`
}

// ChainAddressData defines model for chainAddressData.
type ChainAddressData struct {
	Email string `json:"email"`
	Type  string `json:"type"`
}

// ChainData defines model for chainData.
type ChainData struct {
	FromEmail       string           `json:"from_email"`
	Hash            string           `json:"hash"`
	OrigFromAddress ChainAddressData `json:"orig_from_address"`
	OrigToAddress   ChainAddressData `json:"orig_to_address"`
	ToEmail         string           `json:"to_email"`
}

// DomainData defines model for domainData.
type DomainData struct {
	Active bool `json:"active"`

	// Id Domain ULID
	Id string `json:"id"`

	// Name Domain name (e.g. example.com)
	Name  string    `json:"name"`
	Owner *UserData `json:"owner,omitempty"`

	// Type Enum defining type of the custom domain.
	Type DomainType `json:"type"`

	// Verified Present only for personal domains
	Verified *bool `json:"verified,omitempty"`

	// VerifiedAt Present only for personal domains
	VerifiedAt *time.Time `json:"verified_at,omitempty"`
}

// DomainType Enum defining type of the custom domain.
type DomainType string

// Error defines model for error.
type Error struct {
	// Detail Error details
	Detail string `json:"detail"`

	// Status HTTP status
	Status string `json:"status"`
}

// PaginationMetadata defines model for paginationMetadata.
type PaginationMetadata struct {
	CurrentPage  int `json:"current_page"`
	FirstPage    int `json:"first_page"`
	LastPage     int `json:"last_page"`
	PageSize     int `json:"page_size"`
	TotalRecords int `json:"total_records"`
}

// ProtectedAddressData defines model for protectedAddressData.
type ProtectedAddressData struct {
	// Active Indicates whether the Protected Address is active and can be used
	Active   *bool               `json:"active,omitempty"`
	Email    openapi_types.Email `json:"email"`
	Id       string              `json:"id"`
	Metadata *AddressMetadata    `json:"metadata,omitempty"`
	Owner    UserData            `json:"owner"`
}

// SystemVersionData defines model for systemVersionData.
type SystemVersionData struct {
	// BuiltAt Build timestamp
	BuiltAt string `json:"built_at"`

	// GitCommit Git commit ID (full)
	GitCommit string `json:"git_commit"`

	// Version Semantic version number
	Version string `json:"version"`
}

// UserData defines model for userData.
type UserData struct {
	// Active Indicates whether the user is active
	Active *bool `json:"active,omitempty"`

	// FailedAttempts number of failed authentication attempts
	FailedAttempts *int `json:"failed_attempts,omitempty"`

	// FirstName user first name
	FirstName string `json:"first_name"`

	// Id user id
	Id string `json:"id"`

	// LastName user last name
	LastName string `json:"last_name"`

	// LockoutUntil date/time the user account was lockout until
	LockoutUntil *string `json:"lockout_until,omitempty"`

	// Login user login (for OIDC support should be formatted as email)
	Login string `json:"login"`

	// Type user type
	Type string `json:"type"`
}

// HTTP400 defines model for HTTP400.
type HTTP400 = Error

// HTTP401 defines model for HTTP401.
type HTTP401 = Error

// HTTP403 defines model for HTTP403.
type HTTP403 = Error

// HTTP404 defines model for HTTP404.
type HTTP404 = Error

// AuthForm defines model for authForm.
type AuthForm = BasicAuthForm

// BasicAuthenticationTokenResponse defines model for basicAuthenticationTokenResponse.
type BasicAuthenticationTokenResponse struct {
	// Expiry time of token expiration
	Expiry string `json:"expiry"`

	// Token signed JWT token for stateless authentication
	Token string `json:"token"`
}

// CreateAliasResponse Address of type "alias" data structure
type CreateAliasResponse = AliasData

// CreateApiTokenResponse defines model for createApiTokenResponse.
type CreateApiTokenResponse = ApiTokenDataOnCreate

// CreateDomainResponse defines model for createDomainResponse.
type CreateDomainResponse = DomainData

// CreateEmailChainResponse defines model for createEmailChainResponse.
type CreateEmailChainResponse = ChainData

// CreatePrAddrResponse defines model for createPrAddrResponse.
type CreatePrAddrResponse = ProtectedAddressData

// CreateUserResponse defines model for createUserResponse.
type CreateUserResponse = UserData

// ErrorResponse defines model for errorResponse.
type ErrorResponse struct {
	Errors []Error `json:"errors"`
}

// GetAliasDetailsResponse Address of type "alias" data structure
type GetAliasDetailsResponse = AliasData

// GetAliasesResponse defines model for getAliasesResponse.
type GetAliasesResponse struct {
	Aliases            []AliasData        `json:"aliases"`
	PaginationMetadata PaginationMetadata `json:"pagination_metadata"`
}

// GetApiTokenDetailsResponse defines model for getApiTokenDetailsResponse.
type GetApiTokenDetailsResponse = ApiTokenData

// GetApiTokensResponse defines model for getApiTokensResponse.
type GetApiTokensResponse = []ApiTokenData

// GetDomainsResponse defines model for getDomainsResponse.
type GetDomainsResponse struct {
	Domains []DomainData `json:"domains"`
}

// GetEmailChainDetailsResponse defines model for getEmailChainDetailsResponse.
type GetEmailChainDetailsResponse = ChainData

// GetPrAddrDetailsResponse defines model for getPrAddrDetailsResponse.
type GetPrAddrDetailsResponse = ProtectedAddressData

// GetPrAddrsResponse defines model for getPrAddrsResponse.
type GetPrAddrsResponse struct {
	PaginationMetadata PaginationMetadata     `json:"pagination_metadata"`
	ProtectedAddresses []ProtectedAddressData `json:"protected_addresses"`
}

// GetSystemVersionResponse defines model for getSystemVersionResponse.
type GetSystemVersionResponse = SystemVersionData

// GetUserDetailsResponse defines model for getUserDetailsResponse.
type GetUserDetailsResponse = UserData

// GetUsersResponse defines model for getUsersResponse.
type GetUsersResponse struct {
	PaginationMetadata PaginationMetadata `json:"pagination_metadata"`
	Users              []UserData         `json:"users"`
}

// UpdateAliasResponse Address of type "alias" data structure
type UpdateAliasResponse = AliasData

// UpdateApiTokenResponse defines model for updateApiTokenResponse.
type UpdateApiTokenResponse = ApiTokenData

// UpdateDomainResponse defines model for updateDomainResponse.
type UpdateDomainResponse = DomainData

// UpdatePrAddrResponse defines model for updatePrAddrResponse.
type UpdatePrAddrResponse = ProtectedAddressData

// UpdateUserResponse defines model for updateUserResponse.
type UpdateUserResponse = UserData

// CreateAliasRequest defines model for createAliasRequest.
type CreateAliasRequest struct {
	// DomainId Target domain ID for alias generation
	DomainId           string          `json:"domain_id"`
	Metadata           AddressMetadata `json:"metadata"`
	ProtectedAddressId string          `json:"protected_address_id"`
}

// CreateApiToken defines model for createApiToken.
type CreateApiToken struct {
	Description *string `json:"description,omitempty"`
	ExpireIn    int     `json:"expire_in"`
	Name        string  `json:"name"`
}

// CreateDomainRequest defines model for createDomainRequest.
type CreateDomainRequest struct {
	// Name Domain name (e.g. example.com)
	Name string `json:"name"`

	// Type Enum defining type of the custom domain.
	Type *DomainType `json:"type,omitempty"`
}

// CreateEmailChain defines model for createEmailChain.
type CreateEmailChain struct {
	FromEmail openapi_types.Email `json:"from_email"`
	ToEmail   openapi_types.Email `json:"to_email"`
}

// CreateProtectedAddressRequest defines model for createProtectedAddressRequest.
type CreateProtectedAddressRequest struct {
	Email    string          `json:"email"`
	Metadata AddressMetadata `json:"metadata"`
}

// CreateUserRequest defines model for createUserRequest.
type CreateUserRequest struct {
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Login     string  `json:"login"`
	Password  *string `json:"password,omitempty"`
	Type      string  `json:"type"`
}

// UpdateAliasRequest defines model for updateAliasRequest.
type UpdateAliasRequest struct {
	Active   *bool            `json:"active,omitempty"`
	Metadata *AddressMetadata `json:"metadata,omitempty"`
}

// UpdateApiToken defines model for updateApiToken.
type UpdateApiToken struct {
	Active      *bool   `json:"active,omitempty"`
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// UpdateDomainRequest defines model for updateDomainRequest.
type UpdateDomainRequest struct {
	Active *bool `json:"active,omitempty"`
}

// UpdateProtectedAddressRequest defines model for updateProtectedAddressRequest.
type UpdateProtectedAddressRequest struct {
	Active   *bool            `json:"active,omitempty"`
	Metadata *AddressMetadata `json:"metadata,omitempty"`
}

// UpdateUserRequest defines model for updateUserRequest.
type UpdateUserRequest struct {
	Active    *bool   `json:"active,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	LastName  *string `json:"last_name,omitempty"`
	Type      *string `json:"type,omitempty"`
}

// apiTokenContextKey is the context key for ApiToken security scheme
type apiTokenContextKey string

// basicAuthenticationContextKey is the context key for BasicAuthentication security scheme
type basicAuthenticationContextKey string

// oAuth2ContextKey is the context key for OAuth2 security scheme
type oAuth2ContextKey string

// GetAliasesParams defines parameters for GetAliases.
type GetAliasesParams struct {
	// Owner owner ID to fetch parameters for
	Owner *string `form:"owner,omitempty" json:"owner,omitempty"`

	// Email email of an alias to lookup
	Email *string `form:"email,omitempty" json:"email,omitempty"`

	// Id alias id to retrieve
	Id *string `form:"id,omitempty" json:"id,omitempty"`

	// ServiceName allows to lookup aliases by service name metadata field value
	ServiceName *string `form:"service_name,omitempty" json:"service_name,omitempty"`

	// Q partial-match search across email, service name, and comment
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// CreateAliasJSONBody defines parameters for CreateAlias.
type CreateAliasJSONBody struct {
	// DomainId Target domain ID for alias generation
	DomainId           string          `json:"domain_id"`
	Metadata           AddressMetadata `json:"metadata"`
	ProtectedAddressId string          `json:"protected_address_id"`
}

// UpdateAliasJSONBody defines parameters for UpdateAlias.
type UpdateAliasJSONBody struct {
	Active   *bool            `json:"active,omitempty"`
	Metadata *AddressMetadata `json:"metadata,omitempty"`
}

// GetDomainsParams defines parameters for GetDomains.
type GetDomainsParams struct {
	// DomainName FQDN to lookup within the scope available to the user
	DomainName *string `form:"domain_name,omitempty" json:"domain_name,omitempty"`

	// Active include domains with defined 'active' value (true or false)
	Active *string `form:"active,omitempty" json:"active,omitempty"`

	// Verified include domains with defined 'verified' value (true or false)
	Verified *string `form:"verified,omitempty" json:"verified,omitempty"`

	// IncludeGlobal also include global domains in the list
	IncludeGlobal *string `form:"include_global,omitempty" json:"include_global,omitempty"`
}

// CreateDomainJSONBody defines parameters for CreateDomain.
type CreateDomainJSONBody struct {
	// Name Domain name (e.g. example.com)
	Name string `json:"name"`

	// Type Enum defining type of the custom domain.
	Type *DomainType `json:"type,omitempty"`
}

// UpdateDomainJSONBody defines parameters for UpdateDomain.
type UpdateDomainJSONBody struct {
	Active *bool `json:"active,omitempty"`
}

// GetPrAddrsParams defines parameters for GetPrAddrs.
type GetPrAddrsParams struct {
	Id    *string `form:"id,omitempty" json:"id,omitempty"`
	Email *string `form:"email,omitempty" json:"email,omitempty"`

	// Q partial-match search across email and comment
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// CreatePrAddrJSONBody defines parameters for CreatePrAddr.
type CreatePrAddrJSONBody struct {
	Email    string          `json:"email"`
	Metadata AddressMetadata `json:"metadata"`
}

// UpdatePrAddrJSONBody defines parameters for UpdatePrAddr.
type UpdatePrAddrJSONBody struct {
	Active   *bool            `json:"active,omitempty"`
	Metadata *AddressMetadata `json:"metadata,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// Id user id filter
	Id *string `form:"id,omitempty" json:"id,omitempty"`

	// Login user login filter
	Login *string `form:"login,omitempty" json:"login,omitempty"`

	// Type user type filter
	Type *string `form:"type,omitempty" json:"type,omitempty"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody struct {
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Login     string  `json:"login"`
	Password  *string `json:"password,omitempty"`
	Type      string  `json:"type"`
}

// CreateApiTokenJSONBody defines parameters for CreateApiToken.
type CreateApiTokenJSONBody struct {
	Description *string `json:"description,omitempty"`
	ExpireIn    int     `json:"expire_in"`
	Name        string  `json:"name"`
}

// UpdateApiTokenJSONBody defines parameters for UpdateApiToken.
type UpdateApiTokenJSONBody struct {
	Active      *bool   `json:"active,omitempty"`
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody struct {
	Active    *bool   `json:"active,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	LastName  *string `json:"last_name,omitempty"`
	Type      *string `json:"type,omitempty"`
}

// CreateChainJSONBody defines parameters for CreateChain.
type CreateChainJSONBody struct {
	FromEmail openapi_types.Email `json:"from_email"`
	ToEmail   openapi_types.Email `json:"to_email"`
}

// CreateAliasJSONRequestBody defines body for CreateAlias for application/json ContentType.
type CreateAliasJSONRequestBody CreateAliasJSONBody

// UpdateAliasJSONRequestBody defines body for UpdateAlias for application/json ContentType.
type UpdateAliasJSONRequestBody UpdateAliasJSONBody

// CreateDomainJSONRequestBody defines body for CreateDomain for application/json ContentType.
type CreateDomainJSONRequestBody CreateDomainJSONBody

// UpdateDomainJSONRequestBody defines body for UpdateDomain for application/json ContentType.
type UpdateDomainJSONRequestBody UpdateDomainJSONBody

// CreatePrAddrJSONRequestBody defines body for CreatePrAddr for application/json ContentType.
type CreatePrAddrJSONRequestBody CreatePrAddrJSONBody

// UpdatePrAddrJSONRequestBody defines body for UpdatePrAddr for application/json ContentType.
type UpdatePrAddrJSONRequestBody UpdatePrAddrJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// CreateApiTokenJSONRequestBody defines body for CreateApiToken for application/json ContentType.
type CreateApiTokenJSONRequestBody CreateApiTokenJSONBody

// UpdateApiTokenJSONRequestBody defines body for UpdateApiToken for application/json ContentType.
type UpdateApiTokenJSONRequestBody UpdateApiTokenJSONBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody

// CreateChainJSONRequestBody defines body for CreateChain for application/json ContentType.
type CreateChainJSONRequestBody CreateChainJSONBody
