// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

// Alias defines model for alias.
type Alias struct {
	Active           bool             `json:"active,omitempty"`
	Comment          string           `json:"comment,omitempty"`
	Email            Email            `json:"email"`
	Id               Id               `json:"id,omitempty"`
	ProtectedAddress ProtectedAddress `json:"protected_address,omitempty"`
	ServiceName      ServiceName      `json:"service_name"`
}

// AliasEmailDeleteResponse defines model for alias-email-delete-response.
type AliasEmailDeleteResponse = AliasEmailGetResponse

// AliasEmailGetResponse defines model for alias-email-get-response.
type AliasEmailGetResponse struct {
	Alias Alias `json:"alias"`
}

// AliasesGetResponse defines model for aliases-get-response.
type AliasesGetResponse = []Alias

// AliasesPostResponse defines model for aliases-post-response.
type AliasesPostResponse struct {
	Alias Alias `json:"alias"`
}

// Email defines model for email.
type Email = string

// Error defines model for error.
type Error struct {
	ErrorDescription string `json:"error_description"`
	ErrorId          int    `json:"error_id"`
}

// Id defines model for id.
type Id = string

// ProtectedAddress defines model for protected-address.
type ProtectedAddress struct {
	Active bool   `json:"active,omitempty"`
	Email  Email  `json:"email"`
	Id     string `json:"id"`
}

// ServiceName defines model for service_name.
type ServiceName = string

// PostAliasesJSONRequestBody defines body for PostAliases for application/json ContentType.
type PostAliasesJSONRequestBody = Alias

// PostProtectedAddressesJSONRequestBody defines body for PostProtectedAddresses for application/json ContentType.
type PostProtectedAddressesJSONRequestBody = ProtectedAddress
