package config

// DO NOT EDIT - Code generated by https://github.com/Burmuley/disconfig
type OvooConfig struct {
	Api    APIConfig    `json:"api,required"`
	Milter MilterConfig `json:"milter,required"`
}

func NewOvooConfig(api APIConfig, milter MilterConfig) *OvooConfig {
	return &OvooConfig{
		Api:    api,
		Milter: milter,
	}
}

type APIConfig struct {
	Cache        *APICacheConfig          `json:"cache"`
	Database     APIDBConfig              `json:"database,required"`
	DefaultAdmin APIDefaultAdminConfig    `json:"default_admin,required"`
	Domain       string                   `json:"domain,required"`
	ListenAddr   string                   `json:"listen_addr"`
	Log          OvooLogConfig            `json:"log,required"`
	OIDC         map[string]APIOIDCConfig `json:"oidc,required"`
	Tls          APITLSConfig             `json:"tls,required"`
}

func NewAPIConfig(database APIDBConfig, defaultadmin APIDefaultAdminConfig, domain string, log OvooLogConfig, oidc map[string]APIOIDCConfig, tls APITLSConfig) *APIConfig {
	return &APIConfig{
		Cache:        nil,
		Database:     database,
		DefaultAdmin: defaultadmin,
		Domain:       domain,
		ListenAddr:   "127.0.0.1:8808",
		Log:          log,
		OIDC:         oidc,
		Tls:          tls,
	}
}

type OvooLogConfig struct {
	Destination string `json:"destination,required"`
	Level       string `json:"level,required"`
}

func NewOvooLogConfig(destination string, level string) *OvooLogConfig {
	return &OvooLogConfig{
		Destination: destination,
		Level:       level,
	}
}

type APITLSConfig struct {
	Cert string `json:"cert,required"`
	Key  string `json:"key,required"`
}

func NewAPITLSConfig(cert string, key string) *APITLSConfig {
	return &APITLSConfig{
		Cert: cert,
		Key:  key,
	}
}

type APIDefaultAdminConfig struct {
	FirstName string `json:"first_name,required"`
	LastName  string `json:"last_name,required"`
	Login     string `json:"login,required"`
	Password  string `json:"password,required"`
}

func NewAPIDefaultAdminConfig(firstname string, lastname string, login string, password string) *APIDefaultAdminConfig {
	return &APIDefaultAdminConfig{
		FirstName: firstname,
		LastName:  lastname,
		Login:     login,
		Password:  password,
	}
}

type APIOIDCConfig struct {
	ClientId     string `json:"client_id,required"`
	ClientSecret string `json:"client_secret,required"`
	Issuer       string `json:"issuer,required"`
}

func NewAPIOIDCConfig(clientid string, clientsecret string, issuer string) *APIOIDCConfig {
	return &APIOIDCConfig{
		ClientId:     clientid,
		ClientSecret: clientsecret,
		Issuer:       issuer,
	}
}

type APICacheConfig struct {
	CacheDriver   string               `json:"driver,required"`
	Config        APICacheDriverConfig `json:"config,required"`
	ListTTL       int                  `json:"list_ttl,required"`
	SingleItemTTL int                  `json:"single_item_ttl,required"`
}

func NewAPICacheConfig(cachedriver string, config APICacheDriverConfig, listttl int, singleitemttl int) *APICacheConfig {
	return &APICacheConfig{
		CacheDriver:   cachedriver,
		Config:        config,
		ListTTL:       listttl,
		SingleItemTTL: singleitemttl,
	}
}

type APICacheDriverConfig struct {
	Redis *APICacheDriverRedisConfig `json:"redis"`
}

func NewAPICacheDriverConfig() *APICacheDriverConfig {
	return &APICacheDriverConfig{
		Redis: nil,
	}
}

type APICacheDriverRedisConfig struct {
	Addr     *string `json:"addr"`
	DB       int     `json:"db"`
	Password *string `json:"password,required"`
	Protocol int     `json:"protocol"`
	Username *string `json:"username"`
}

func NewAPICacheDriverRedisConfig(password *string) *APICacheDriverRedisConfig {
	return &APICacheDriverRedisConfig{
		Addr:     nil,
		DB:       0,
		Password: password,
		Protocol: 3,
		Username: nil,
	}
}

type APIDBConfig struct {
	Config   APIDBDriverConfig `json:"config,required"`
	DBType   string            `json:"type,required"`
	LogLevel string            `json:"log_level,required"`
}

func NewAPIDBConfig(config APIDBDriverConfig, dbtype string, loglevel string) *APIDBConfig {
	return &APIDBConfig{
		Config:   config,
		DBType:   dbtype,
		LogLevel: loglevel,
	}
}

type APIDBDriverConfig struct {
	ConnectionString string `json:"connection_string,required"`
	Driver           string `json:"driver,required"`
}

func NewAPIDBDriverConfig(connectionstring string, driver string) *APIDBDriverConfig {
	return &APIDBDriverConfig{
		ConnectionString: connectionstring,
		Driver:           driver,
	}
}

type MilterConfig struct {
	Api        MilterAPIConfig `json:"api,required"`
	Domain     string          `json:"domain,required"`
	ListenAddr string          `json:"listen_addr"`
	Log        OvooLogConfig   `json:"log,required"`
}

func NewMilterConfig(api MilterAPIConfig, domain string, log OvooLogConfig) *MilterConfig {
	return &MilterConfig{
		Api:        api,
		Domain:     domain,
		ListenAddr: "127.0.0.1:6785",
		Log:        log,
	}
}

type MilterAPIConfig struct {
	Addr          string `json:"addr,required"`
	AuthToken     string `json:"auth_token,required"`
	TlsSkipVerify bool   `json:"tls_skip_verify,required"`
}

func NewMilterAPIConfig(addr string, authtoken string, tlsskipverify bool) *MilterAPIConfig {
	return &MilterAPIConfig{
		Addr:          addr,
		AuthToken:     authtoken,
		TlsSkipVerify: tlsskipverify,
	}
}
